// Popular and common Israeli names. Adds the ones the app doesn't have yet and fills in
// details for names that were only in the US Social Security list. Names the app already
// describes are left as they are, and spelling variants of names already in the app
// (ph/f, ch/h, tz/z, doubled consonants, a final h) aren't added again.
// Format: Name: [gender, meaning, syllables, style, nicknames]
const ISRAELI_NAMES = {
  // ── Girls ──
  Ahuva:     ['girl', 'beloved', 3, ['vintage'], []],
  Avigail:   ['girl', "my father's joy", 3, ['classic'], ['Avi', 'Gaili']],
  Ayala:     ['girl', 'doe, gazelle', 3, ['classic', 'nature'], []],
  Ayelet:    ['girl', 'doe; the morning star', 3, ['classic'], []],
  Batsheva:  ['girl', 'daughter of the oath', 3, ['vintage'], ['Sheva']],
  Bracha:    ['girl', 'blessing', 2, ['vintage'], []],
  Dafna:     ['girl', 'laurel', 2, ['nature'], []],
  Efrat:     ['girl', 'fruitful', 2, ['classic'], []],
  Einav:     ['girl', 'grape', 2, ['nature'], []],
  Elinor:    ['girl', 'God is my light', 3, ['modern'], []],
  Elisheva:  ['girl', 'God is my oath', 4, ['classic'], ['Sheva']],
  Emuna:     ['girl', 'faith', 3, ['classic'], []],
  Gali:      ['girl', 'my wave', 2, ['nature'], []],
  Galit:     ['girl', 'wave', 2, ['nature', 'vintage'], []],
  Gefen:     ['girl', 'grapevine', 2, ['nature'], []],
  Gila:      ['girl', 'joy', 2, ['vintage'], []],
  Hadar:     ['girl', 'splendor, glory', 2, ['classic'], []],
  Hadas:     ['girl', 'myrtle', 2, ['nature'], []],
  Hagar:     ['girl', 'flight; mother of Ishmael in the Bible', 2, ['classic'], []],
  Hagit:     ['girl', 'festive, joyful', 2, ['vintage'], []],
  Hen:       ['girl', 'grace, charm', 1, ['modern'], []],
  Hila:      ['girl', 'halo; praise', 2, ['modern'], []],
  Hodaya:    ['girl', 'thanksgiving, praise to God', 3, ['classic'], []],
  Ilanit:    ['girl', 'little tree', 3, ['nature', 'vintage'], []],
  Inbal:     ['girl', 'the clapper of a bell', 2, ['modern'], []],
  Irit:      ['girl', 'asphodel (a wildflower)', 2, ['nature', 'vintage'], []],
  Karmel:    ['girl', 'vineyard of God; Mount Carmel', 2, ['nature'], []],
  Keren:     ['girl', 'ray of light', 2, ['classic'], []],
  Kinneret:  ['girl', 'the Sea of Galilee, from the word for harp', 3, ['nature', 'unique'], []],
  Libi:      ['girl', 'my heart', 2, ['modern'], []],
  Liel:      ['girl', 'the night is mine; God is mine', 2, ['modern'], []],
  Lihi:      ['girl', 'she is mine', 2, ['modern'], []],
  Limor:     ['girl', 'myrrh is mine', 2, ['vintage'], []],
  Liraz:     ['girl', 'my secret', 2, ['modern'], []],
  Lital:     ['girl', 'the dew is mine', 2, ['modern'], []],
  Maayan:    ['girl', 'spring of water', 3, ['nature'], []],
  Malka:     ['girl', 'queen', 2, ['vintage'], []],
  Margalit:  ['girl', 'pearl', 3, ['vintage'], []],
  Mazal:     ['girl', 'luck, good fortune', 2, ['vintage'], []],
  Meital:    ['girl', 'dew drop', 2, ['modern'], []],
  Merav:     ['girl', 'abundance', 2, ['vintage'], []],
  Mika:      ['girl', 'who is like God?', 2, ['modern'], []],
  Miri:      ['girl', 'a short form of Miriam', 2, ['vintage'], []],
  Mor:       ['girl', 'myrrh', 1, ['modern'], []],
  Moran:     ['girl', 'viburnum (a flowering shrub)', 2, ['nature'], []],
  Naama:     ['girl', 'pleasant, delightful', 3, ['classic'], []],
  Nava:      ['girl', 'beautiful', 2, ['classic'], []],
  Nechama:   ['girl', 'comfort', 3, ['vintage'], []],
  Neta:      ['girl', 'plant, sapling', 2, ['nature', 'modern'], []],
  Noga:      ['girl', 'brightness; the planet Venus', 2, ['classic'], []],
  Noya:      ['girl', 'beauty of God', 2, ['modern'], []],
  Nurit:     ['girl', 'buttercup (a wildflower)', 2, ['nature', 'vintage'], []],
  Odelia:    ['girl', 'I will praise God', 4, ['classic'], []],
  Ofra:      ['girl', 'young deer', 2, ['vintage'], []],
  Ofri:      ['girl', 'my fawn', 2, ['modern'], []],
  Orit:      ['girl', 'light', 2, ['vintage'], []],
  Oriya:     ['girl', 'light of God', 3, ['modern'], []],
  Orly:      ['girl', 'my light', 2, ['vintage'], []],
  Orna:      ['girl', 'pine tree; light', 2, ['vintage'], []],
  Ortal:     ['girl', 'dew of light', 2, ['modern'], []],
  Osnat:     ['girl', 'wife of Joseph in the Bible', 2, ['vintage'], []],
  Reut:      ['girl', 'friendship', 2, ['classic'], []],
  Rina:      ['girl', 'joy, song', 2, ['vintage'], []],
  Rinat:     ['girl', 'joyful song', 2, ['modern'], []],
  Romi:      ['girl', 'my exaltation, height', 2, ['modern'], []],
  Rona:      ['girl', 'my joy, my song', 2, ['modern'], []],
  Roni:      ['girl', 'my joy, my song', 2, ['modern'], []],
  Ronit:     ['girl', 'joy, song', 2, ['vintage'], []],
  Sapir:     ['girl', 'sapphire', 2, ['modern'], []],
  Sarit:     ['girl', 'princess', 2, ['vintage'], []],
  Shani:     ['girl', 'scarlet', 2, ['modern'], []],
  Shiran:    ['girl', 'song of joy', 2, ['modern'], []],
  Shirel:    ['girl', 'song of God', 2, ['modern'], []],
  Shlomit:   ['girl', 'peaceful', 2, ['vintage'], []],
  Shoshana:  ['girl', 'lily, rose', 3, ['vintage', 'nature'], []],
  Shulamit:  ['girl', 'peaceful', 3, ['vintage'], []],
  Sigal:     ['girl', 'treasure; violet', 2, ['vintage'], []],
  Sivan:     ['girl', 'a spring month of the Hebrew calendar', 2, ['nature'], []],
  Smadar:    ['girl', 'grape blossom', 2, ['nature', 'vintage'], []],
  Tali:      ['girl', 'my dew', 2, ['modern'], []],
  Tehila:    ['girl', 'praise, glory', 3, ['classic'], []],
  Tirtza:    ['girl', 'favorable, pleasant', 2, ['vintage'], []],
  Tzipora:   ['girl', 'bird; wife of Moses', 3, ['vintage'], []],
  Tzofia:    ['girl', 'one who watches over', 3, ['modern'], []],
  Yaara:     ['girl', 'honeycomb; forest', 3, ['nature'], []],
  Yafit:     ['girl', 'beautiful', 2, ['vintage'], []],
  Yehudit:   ['girl', 'praised; woman of Judea', 3, ['classic'], []],
  Yemima:    ['girl', 'dove; a daughter of Job', 3, ['vintage'], []],
  Yiska:     ['girl', 'to see, to foresee', 2, ['unique'], []],
  Yonit:     ['girl', 'little dove', 2, ['vintage'], []],

  // ── Boys ──
  Adiel:     ['boy', 'ornament of God', 3, ['modern'], []],
  Akiva:     ['boy', 'protected; held by the heel', 3, ['classic'], []],
  Alon:      ['boy', 'oak tree', 2, ['nature'], []],
  Amichai:   ['boy', 'my people live', 3, ['modern'], []],
  Amit:      ['boy', 'friend, companion', 2, ['modern'], []],
  Amitai:    ['boy', 'truthful', 3, ['classic'], []],
  Arbel:     ['boy', 'a mountain in the Galilee', 2, ['nature'], []],
  Ari:       ['boy', 'lion', 2, ['classic'], []],
  Ariel:     ['boy', 'lion of God', 3, ['classic'], ['Ari']],
  Asaf:      ['boy', 'gatherer', 2, ['classic'], []],
  Avinoam:   ['boy', 'my father is pleasantness', 4, ['classic'], ['Avi']],
  Avishai:   ['boy', 'gift of my father', 3, ['classic'], ['Avi']],
  Aviv:      ['boy', 'spring (the season)', 2, ['nature'], []],
  Avraham:   ['boy', 'father of many nations', 3, ['classic'], ['Avi']],
  Barak:     ['boy', 'lightning', 2, ['classic'], []],
  Ben:       ['boy', 'son', 1, ['classic'], []],
  Binyamin:  ['boy', 'son of the right hand', 3, ['classic'], ['Bini']],
  Doron:     ['boy', 'gift', 2, ['classic'], []],
  Dor:       ['boy', 'generation', 1, ['modern'], []],
  Dvir:      ['boy', 'the inner sanctuary of the Temple', 2, ['modern'], []],
  Ehud:      ['boy', 'united, sympathetic', 2, ['vintage'], []],
  Elad:      ['boy', 'God is eternal', 2, ['modern'], []],
  Eliav:     ['boy', 'my God is father', 3, ['modern'], []],
  Eliya:     ['boy', 'my God is the Lord', 3, ['modern'], []],
  Elisha:    ['boy', 'God is salvation', 3, ['classic'], []],
  Elkana:    ['boy', 'God has acquired', 3, ['vintage'], []],
  Erel:      ['boy', 'brave; an angel', 2, ['modern'], []],
  Evyatar:   ['boy', 'father of abundance', 3, ['classic'], []],
  Gad:       ['boy', 'good fortune', 1, ['classic'], []],
  Gavriel:   ['boy', 'God is my strength', 3, ['classic'], []],
  Gilad:     ['boy', 'mound of testimony; a region east of the Jordan', 2, ['classic'], []],
  Hagai:     ['boy', 'festive; a biblical prophet', 2, ['classic'], []],
  Harel:     ['boy', 'mountain of God', 2, ['modern'], []],
  Hod:       ['boy', 'splendor, majesty', 1, ['modern'], []],
  Ido:       ['boy', 'timely; a biblical prophet', 2, ['modern'], []],
  Ilai:      ['boy', 'exalted, superior', 2, ['modern'], []],
  Itiel:     ['boy', 'God is with me', 3, ['modern'], []],
  Kfir:      ['boy', 'lion cub', 1, ['modern'], []],
  Lahav:     ['boy', 'flame; blade', 2, ['modern'], []],
  Lavi:      ['boy', 'lion', 2, ['modern'], []],
  Maor:      ['boy', 'light, luminary', 2, ['modern'], []],
  Meir:      ['boy', 'one who gives light', 2, ['classic'], []],
  Menachem:  ['boy', 'comforter', 3, ['vintage'], ['Mendy']],
  Naftali:   ['boy', 'my struggle; a son of Jacob', 3, ['classic'], []],
  Nehemia:   ['boy', 'comforted by God', 4, ['classic'], []],
  Nehorai:   ['boy', 'light', 3, ['modern'], []],
  Neriya:    ['boy', 'light of God', 3, ['modern'], []],
  Netanel:   ['boy', 'gift of God', 3, ['classic'], ['Neti']],
  Nevo:      ['boy', 'Mount Nebo', 2, ['nature'], []],
  Nimrod:    ['boy', 'rebel; a mighty hunter in the Bible', 2, ['classic'], []],
  Nir:       ['boy', 'plowed field', 1, ['modern'], []],
  Oded:      ['boy', 'restorer, encourager', 2, ['vintage'], []],
  Ofek:      ['boy', 'horizon', 2, ['modern'], []],
  Ofer:      ['boy', 'young deer, fawn', 2, ['vintage'], []],
  Ohad:      ['boy', 'beloved', 2, ['modern'], []],
  Omri:      ['boy', 'my sheaf; a king of Israel', 2, ['modern'], []],
  Oshri:     ['boy', 'my good fortune', 2, ['modern'], []],
  Oz:        ['boy', 'strength', 1, ['modern'], []],
  Peleg:     ['boy', 'stream; division', 2, ['unique'], []],
  Pinchas:   ['boy', 'a biblical priest; from Egyptian, "the Nubian"', 2, ['vintage'], []],
  Raz:       ['boy', 'secret', 1, ['modern'], []],
  Ran:       ['boy', 'joyful, singing', 1, ['modern'], []],
  Ravid:     ['boy', 'necklace, ornament', 2, ['modern'], []],
  Raviv:     ['boy', 'rain, dew', 2, ['nature'], []],
  Refael:    ['boy', 'God heals', 3, ['classic'], ['Rafi']],
  Reuven:    ['boy', 'behold, a son', 2, ['classic'], []],
  Roi:       ['boy', 'my shepherd', 2, ['modern'], []],
  Ronen:     ['boy', 'singing, joyful', 2, ['modern'], []],
  Sagi:      ['boy', 'sublime, mighty', 2, ['modern'], []],
  Segev:     ['boy', 'exalted, majestic', 2, ['modern'], []],
  Shalev:    ['boy', 'calm, peaceful', 2, ['modern'], []],
  Shimshon:  ['boy', 'of the sun (Samson)', 2, ['vintage'], []],
  Shmuel:    ['boy', 'God has heard', 2, ['classic'], ['Shmulik']],
  Snir:      ['boy', 'a peak of Mount Hermon', 1, ['nature'], []],
  Tavor:     ['boy', 'Mount Tabor', 2, ['nature'], []],
  Tomer:     ['boy', 'palm tree', 2, ['nature', 'modern'], []],
  Tuvia:     ['boy', 'God is good', 3, ['classic'], []],
  Tzur:      ['boy', 'rock', 1, ['modern'], []],
  Tzvi:      ['boy', 'deer', 1, ['classic'], []],
  Uriel:     ['boy', 'God is my light', 3, ['classic'], []],
  Yaakov:    ['boy', 'held by the heel; Jacob', 3, ['classic'], ['Kobi']],
  Yaniv:     ['boy', 'he will flourish', 2, ['modern'], []],
  Yechezkel: ['boy', 'God strengthens (Ezekiel)', 3, ['vintage'], []],
  Yechiel:   ['boy', 'may God live', 3, ['vintage'], []],
  Yedidya:   ['boy', 'friend of God', 4, ['classic'], []],
  Yehonatan: ['boy', 'God has given', 4, ['classic'], []],
  Yehoshua:  ['boy', 'God is salvation (Joshua)', 3, ['classic'], ['Shuki']],
  Yehuda:    ['boy', 'praised (Judah)', 3, ['classic'], []],
  Yiftach:   ['boy', 'he will open', 2, ['vintage'], []],
  Yigal:     ['boy', 'he will redeem', 2, ['vintage'], []],
  Yinon:     ['boy', 'he will flourish', 2, ['modern'], []],
  Yishai:    ['boy', 'gift (Jesse)', 2, ['classic'], []],
  Yisrael:   ['boy', 'one who struggles with God', 3, ['classic'], ['Srulik']],
  Yitzhak:   ['boy', 'he will laugh (Isaac)', 2, ['classic'], ['Itzik']],
  Yoel:      ['boy', 'the Lord is God (Joel)', 2, ['classic'], []],
  Yosef:     ['boy', 'God will add (Joseph)', 2, ['classic'], ['Yossi']],
  Yotam:     ['boy', 'God is perfect', 2, ['modern'], []],

  // ── Unisex ──
  Adi:       ['either', 'jewel, ornament', 2, ['modern'], []],
  Agam:      ['either', 'lake', 2, ['nature', 'modern'], []],
  Bar:       ['either', 'wild; field', 1, ['modern'], []],
  Gil:       ['either', 'joy', 1, ['modern'], []],
  Hallel:    ['either', 'praise', 2, ['modern'], []],
  Keshet:    ['either', 'rainbow', 2, ['nature'], []],
  Liad:      ['either', 'mine forever', 2, ['modern'], []],
  Lior:      ['either', 'my light', 2, ['modern'], []],
  Liron:     ['either', 'my song', 2, ['modern'], []],
  Nitzan:    ['either', 'blossom, bud', 2, ['nature'], []],
  Ofir:      ['either', 'gold; a biblical land of gold', 2, ['modern'], []],
  Or:        ['either', 'light', 1, ['modern'], []],
  Paz:       ['either', 'gold', 1, ['modern'], []],
  Rotem:     ['either', 'a white broom shrub of the desert', 2, ['nature'], []],
  Shachar:   ['either', 'dawn', 2, ['modern'], []],
  Shaked:    ['either', 'almond', 2, ['nature'], []],
  Sharon:    ['either', 'a fertile coastal plain', 2, ['classic'], []],
  Shir:      ['either', 'song', 1, ['modern'], []],
  Shoham:    ['either', 'onyx', 2, ['modern'], []],
  Stav:      ['either', 'autumn', 1, ['nature'], []],
  Tal:       ['either', 'dew', 1, ['modern'], []],
  Yarden:    ['either', 'to flow down; the Jordan River', 2, ['nature'], []],
  Ziv:       ['either', 'radiance', 1, ['modern'], []],
  Zohar:     ['either', 'radiance, brilliance', 2, ['classic'], []],
};

(function addIsraeliNames() {
  // Spelling key: ignores case, accents, and common transliteration differences
  const variantKey = s => s.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase()
    .replace(/ph/g, 'f').replace(/kh|ch/g, 'h').replace(/tz/g, 'z').replace(/ck/g, 'k')
    .replace(/([^aeiou])\1+/g, '$1').replace(/h$/, '');
  const byKey = new Map(NAMES.map(n => [n.name.toLowerCase(), n]));
  const variants = new Map(NAMES.map(n => [variantKey(n.name), n.name]));
  let added = 0, filled = 0;
  const skipped = [];

  for (const [name, [gender, meaning, syllables, style, nicknames]] of Object.entries(ISRAELI_NAMES)) {
    let entry = byKey.get(name.toLowerCase());
    if (!entry) {
      const existing = variants.get(variantKey(name));
      if (existing) { skipped.push(`${name} (${existing})`); continue; }
      entry = { name, gender, origin: [], tradition: [], style: [], meaning: '', syllables: null };
      NAMES.push(entry);
      byKey.set(name.toLowerCase(), entry);
      variants.set(variantKey(name), name);
      added++;
    } else {
      // Only fill what's missing; a name the app already describes keeps its details
      if (entry.meaning && entry.origin.length) continue;
      if (entry.usOnly) entry.gender = gender;   // US-only entries had no details of their own
      filled++;
    }
    delete entry.usOnly;
    if (!entry.meaning) entry.meaning = meaning;
    if (!entry.origin.length) entry.origin = ['hebrew'];
    if (!entry.style.length) entry.style = style;
    if (!entry.tradition.length) entry.tradition = ['jewish', 'secular'];
    if (!Number.isFinite(entry.syllables)) entry.syllables = syllables;
    if (!NICKNAMES[entry.name] && nicknames.length) NICKNAMES[entry.name] = nicknames;
  }
  Object.assign(ISRAELI_NAMES, { added, filled, skipped });
})();
