// Common nicknames, keyed by full name. Names with no well-known short form are left out.
const NICKNAMES = {
  // ── Girls ──
  Abigail: ["Abby", "Gail"],
  Ada: ["Addie"],
  Addison: ["Addie", "Addy"],
  Adelaide: ["Addie", "Della", "Heidi"],
  Adeline: ["Addie", "Lina", "Addy"],
  Agnes: ["Aggie", "Nessa"],
  Alessandra: ["Sandra", "Alessa", "Sasha"],
  Alexandra: ["Alex", "Lexi", "Sasha", "Sandra"],
  Alice: ["Allie", "Ally"],
  Amelia: ["Millie", "Mia", "Amy", "Mel"],
  Amelie: ["Millie", "Mia"],
  Anastasia: ["Ana", "Stasia", "Asya", "Nastya"],
  Anastasiya: ["Nastya", "Asya"],
  Andrea: ["Andi", "Drea"],
  Annabel: ["Annie", "Belle", "Bella"],
  Anna: ["Annie", "Ani"],
  Anneliese: ["Annie", "Lise", "Liesl"],
  Antonia: ["Toni", "Tonia"],
  Arabella: ["Bella", "Bel", "Ara"],
  Ariadne: ["Ari", "Addie"],
  Ariana: ["Ari", "Ana"],
  Astrid: ["Assi"],
  Aurora: ["Rory", "Aura"],
  Barbara: ["Barb", "Babs", "Bobbie"],
  Beatrice: ["Bea", "Trixie", "Bee"],
  Beatriz: ["Bea", "Bia"],
  Bernadette: ["Bernie", "Detta"],
  Bethan: ["Beth"],
  Bianca: ["Bia"],
  Bohdana: ["Dana"],
  Callie: ["Cal"],
  Calliope: ["Callie", "Cali"],
  Callista: ["Callie"],
  Camila: ["Cami", "Mila"],
  Camille: ["Cami", "Millie"],
  Carlotta: ["Lotta", "Carly"],
  Carolina: ["Carol", "Lina", "Caro"],
  Caroline: ["Carrie", "Carly", "Caro"],
  Cassandra: ["Cassie", "Cass", "Sandra"],
  Catalina: ["Cata", "Lina"],
  Caterina: ["Rina", "Cate"],
  Catherine: ["Cathy", "Kate", "Katie", "Cat"],
  Catriona: ["Cat", "Trina"],
  Cecilia: ["Cece", "Celia", "Cissy"],
  Cecily: ["Cece", "Cissy"],
  Celeste: ["Cece", "Celie"],
  Charlotte: ["Lottie", "Charlie", "Lotte"],
  Christine: ["Chris", "Chrissy", "Tina"],
  Clara: ["Clare"],
  Clementine: ["Clem", "Clemmie", "Tina"],
  Constance: ["Connie"],
  Cordelia: ["Cordy", "Delia"],
  Cosima: ["Cosi"],
  Cynthia: ["Cindy", "Cyn"],
  Daphne: ["Daph"],
  Delilah: ["Lila", "Del"],
  Diana: ["Di"],
  Dolores: ["Lola", "Dolly"],
  Dorothy: ["Dot", "Dottie", "Dora"],
  Edith: ["Edie"],
  Ekaterina: ["Katya", "Katia"],
  Eleanor: ["Ellie", "Nora", "Nell", "Elle"],
  Eleonora: ["Ellie", "Nora", "Leo"],
  Elena: ["Ellie", "Lena"],
  Eliana: ["Ellie", "Liana"],
  Eliza: ["Liza", "Ellie"],
  Elizabeth: ["Liz", "Lizzie", "Beth", "Eliza", "Ellie", "Betsy"],
  Eloise: ["Ellie", "Lou"],
  Emilia: ["Emmy", "Millie", "Mila"],
  Emily: ["Em", "Emmy", "Millie"],
  Emma: ["Em", "Emmy"],
  Esmeralda: ["Esme"],
  Esperanza: ["Espe"],
  Esther: ["Essie", "Etty"],
  Eugenie: ["Genie"],
  Evangeline: ["Evie", "Eva", "Angie"],
  Evelyn: ["Evie", "Eve", "Lyn"],
  Everly: ["Evie"],
  Felicity: ["Fliss", "Flick"],
  Florence: ["Flo", "Flora", "Florrie"],
  Frances: ["Frankie", "Fran", "Franny"],
  Francesca: ["Frankie", "Fran", "Chessa"],
  Frederica: ["Freddie"],
  Gabriella: ["Gabby", "Ella", "Bri"],
  Gabrielle: ["Gabby", "Elle"],
  Genevieve: ["Gen", "Evie", "Vivi"],
  Georgia: ["George", "Gigi"],
  Georgina: ["George", "Gina"],
  Ginevra: ["Ginny", "Neve"],
  Giulia: ["Giuli"],
  Gwendolyn: ["Gwen", "Wendy"],
  Hadassah: ["Dassi"],
  Hannah: ["Annie", "Han"],
  Harriet: ["Hattie", "Harry", "Etta"],
  Hazel: ["Haze"],
  Helena: ["Lena", "Nell"],
  Imogen: ["Immy", "Midge"],
  Isabel: ["Izzy", "Bella", "Isa"],
  Isabella: ["Izzy", "Bella", "Isa"],
  Isabelle: ["Izzy", "Belle", "Isa"],
  Isadora: ["Izzy", "Dora"],
  Jacqueline: ["Jackie"],
  Jasmine: ["Jas", "Jazzy"],
  Jessica: ["Jess", "Jessie"],
  Jimena: ["Jime"],
  Josephine: ["Josie", "Jo", "Posy"],
  Joséphine: ["Josie", "Jo"],
  Judith: ["Judy", "Jude"],
  Julia: ["Jules", "Julie"],
  Juliette: ["Jules", "Julie", "Etta"],
  Juniper: ["June", "Juni"],
  Katherine: ["Kate", "Katie", "Kat", "Kathy"],
  Kathleen: ["Kath", "Kathy", "Kate"],
  Lillian: ["Lily", "Lil"],
  Lourdes: ["Lulu"],
  Louisa: ["Lou", "Lulu"],
  Louise: ["Lou", "Lulu"],
  Lucia: ["Lucy", "Lu"],
  Luciana: ["Lucy", "Lu", "Ana"],
  Lucille: ["Lucy", "Lu"],
  Madison: ["Maddie"],
  Margaret: ["Maggie", "Meg", "Peggy", "Daisy", "Greta"],
  Margaux: ["Margo", "Mags"],
  Margot: ["Mags", "Go-Go"],
  Maria: ["Mia", "Ria"],
  Marisol: ["Mari", "Sol"],
  Marina: ["Mari", "Rina"],
  Martha: ["Marty", "Mattie"],
  Mathilde: ["Tilly", "Mattie"],
  Matilda: ["Tilly", "Mattie", "Tilda"],
  Natalia: ["Talia", "Nat", "Natasha"],
  Natalie: ["Nat", "Natty"],
  Natasha: ["Tasha", "Nat"],
  Octavia: ["Tavi", "Via"],
  Olivia: ["Liv", "Livvy", "Ollie"],
  Ophelia: ["Phee", "Lia"],
  Ottilie: ["Tilly", "Lottie"],
  Paloma: ["Palo"],
  Penelope: ["Penny", "Nell", "Poppy"],
  Philippa: ["Pippa", "Pip"],
  Pippa: ["Pip"],
  Rachel: ["Rach"],
  Rebecca: ["Becca", "Becky"],
  Rosalie: ["Rosie", "Ro"],
  Rosalind: ["Rosie", "Roz"],
  Rose: ["Rosie"],
  Samira: ["Sami", "Mira"],
  Savannah: ["Savvy", "Vanna"],
  Scarlett: ["Lettie", "Scar"],
  Serena: ["Rena"],
  Sophia: ["Sophie", "Sofi"],
  Sofia: ["Sofi", "Sophie"],
  Stefania: ["Stef", "Steffi"],
  Susanna: ["Sue", "Suzy", "Sanna"],
  Suzanne: ["Suzy", "Sue"],
  Sylvia: ["Sylvie", "Via"],
  Tatiana: ["Tanya", "Tati"],
  Theodora: ["Thea", "Teddie", "Dora"],
  Valentina: ["Val", "Tina", "Vale"],
  Valeria: ["Val", "Lera"],
  Veronica: ["Ronnie", "Vera", "Nica"],
  Veronika: ["Ronnie", "Nika"],
  Victoria: ["Tori", "Vicky", "Vic"],
  Victoire: ["Vic"],
  Violet: ["Vi", "Lettie"],
  Virginia: ["Ginny", "Ginger"],
  Vittoria: ["Tori"],
  Vivienne: ["Viv", "Vivi"],
  Wilhelmina: ["Willa", "Mina", "Billie", "Minnie"],
  Winifred: ["Winnie", "Freddie"],
  Yaroslava: ["Slava", "Yara"],
  Zahava: ["Zava"],

  // ── Boys ──
  Aaron: ["Ari"],
  Adam: ["Ad"],
  Albert: ["Al", "Bertie", "Albie"],
  Alejandro: ["Alex", "Ale"],
  Alessandro: ["Sandro", "Alex"],
  Alexander: ["Alex", "Xander", "Sasha", "Zander"],
  Alexandre: ["Alex"],
  Alexei: ["Lyosha", "Alyosha"],
  Alfred: ["Alfie", "Fred", "Freddie"],
  Alistair: ["Ali", "Al"],
  Ambrose: ["Bram"],
  Andreas: ["Andy", "Dre"],
  Andres: ["Andy", "Dre"],
  Anthony: ["Tony", "Ant"],
  Antoine: ["Toine"],
  Antonio: ["Tony", "Toni", "Nino"],
  Archibald: ["Archie"],
  Arthur: ["Art", "Artie"],
  Arturo: ["Art", "Turo"],
  Atticus: ["Atti", "Finch"],
  August: ["Gus", "Augie"],
  Augustin: ["Gus", "Augie"],
  Barnaby: ["Barney"],
  Bartholomew: ["Bart"],
  Benedict: ["Ben", "Benny"],
  Benjamin: ["Ben", "Benji", "Benny"],
  Bennett: ["Ben"],
  Bernard: ["Bernie"],
  Callum: ["Cal"],
  Calvin: ["Cal"],
  Cameron: ["Cam"],
  Carlos: ["Carlitos"],
  Casimir: ["Cas", "Kaz"],
  Caspian: ["Cas"],
  Charles: ["Charlie", "Chas", "Chuck"],
  Christopher: ["Chris", "Kit", "Topher"],
  Constantine: ["Con", "Dino", "Costa"],
  Cristobal: ["Cris", "Tobal"],
  Daniel: ["Dan", "Danny"],
  Dashiell: ["Dash"],
  David: ["Dave", "Davy"],
  Dmitri: ["Dima"],
  Dmitry: ["Dima"],
  Dominic: ["Dom", "Nico"],
  Douglas: ["Doug"],
  Edmund: ["Ed", "Eddie", "Ned"],
  Edward: ["Ed", "Eddie", "Ted", "Teddy", "Ned"],
  Elias: ["Eli"],
  Elijah: ["Eli", "Lij"],
  Elliot: ["Eli"],
  Elliott: ["Eli"],
  Emmanuel: ["Manny"],
  Ephraim: ["Eph"],
  Ernest: ["Ernie"],
  Esteban: ["Teban"],
  Eugene: ["Gene"],
  Evander: ["Van", "Evan"],
  Everett: ["Ev", "Rhett"],
  Ezekiel: ["Zeke"],
  Federico: ["Fede", "Rico"],
  Felipe: ["Pipe"],
  Finnegan: ["Finn"],
  Fletcher: ["Fletch"],
  Francisco: ["Paco", "Frankie", "Cisco"],
  Franklin: ["Frank", "Frankie"],
  Frederick: ["Fred", "Freddie", "Rick"],
  Friedrich: ["Fritz"],
  Gabriel: ["Gabe"],
  Gideon: ["Gid"],
  Giovanni: ["Gio", "Gianni"],
  Graham: ["Gray"],
  Gregory: ["Greg"],
  Harold: ["Harry", "Hal"],
  Harrison: ["Harry", "Harris"],
  Henry: ["Hank", "Hal", "Harry"],
  Hudson: ["Huddy"],
  Ignacio: ["Nacho"],
  Isaac: ["Ike", "Zac"],
  Isaiah: ["Izzy"],
  Jackson: ["Jack", "Jax"],
  Jacob: ["Jake", "Coby"],
  James: ["Jamie", "Jim", "Jimmy"],
  Jasper: ["Jas"],
  Javier: ["Javi"],
  Joaquin: ["Quino"],
  John: ["Johnny", "Jack"],
  Jonathan: ["Jon", "Jonny", "Nate"],
  Joseph: ["Joe", "Joey"],
  Joshua: ["Josh"],
  Julian: ["Jules"],
  Konstantin: ["Kostya"],
  Lachlan: ["Lachie", "Lockie"],
  Lawrence: ["Larry", "Laurie"],
  Leander: ["Leo"],
  Leonard: ["Leo", "Len", "Lenny"],
  Leonardo: ["Leo", "Nardo"],
  Leonidas: ["Leo"],
  Leopold: ["Leo", "Poldi"],
  Lincoln: ["Linc"],
  Lorenzo: ["Enzo", "Renzo"],
  Lucas: ["Luke", "Luca"],
  Lysander: ["Sandy", "Zander"],
  Malachi: ["Mal"],
  Malcolm: ["Mal"],
  Manuel: ["Manny", "Manu"],
  Marcus: ["Marc"],
  Matteo: ["Teo"],
  Matthew: ["Matt", "Matty"],
  Matthias: ["Matt", "Thias"],
  Maverick: ["Mav"],
  Maximilian: ["Max", "Milo"],
  Michael: ["Mike", "Mikey", "Mick"],
  Mikhail: ["Misha"],
  Mordecai: ["Mordy"],
  Mykhailo: ["Misha"],
  Nathan: ["Nate"],
  Nicolas: ["Nick", "Nico"],
  Nikolai: ["Kolya", "Nik"],
  Oleksandr: ["Sasha", "Oles"],
  Oliver: ["Ollie", "Olly"],
  Patrick: ["Pat", "Paddy"],
  Percival: ["Percy"],
  Peregrine: ["Perry"],
  Philip: ["Phil", "Pip"],
  Raphael: ["Rafa", "Rafe"],
  Rafael: ["Rafa"],
  Reginald: ["Reggie", "Reg"],
  Reuben: ["Ruby"],
  Robert: ["Rob", "Robbie", "Bobby", "Bob"],
  Rodrigo: ["Rodri", "Rigo"],
  Ronan: ["Ro"],
  Rupert: ["Rupe"],
  Samuel: ["Sam", "Sammy"],
  Santiago: ["Santi", "Diego"],
  Sebastian: ["Seb", "Bash", "Bastian"],
  Sergei: ["Seryozha"],
  Simon: ["Si"],
  Solomon: ["Sol"],
  Spencer: ["Spence"],
  Stanislav: ["Stas"],
  Stanley: ["Stan"],
  Sullivan: ["Sully"],
  Theodore: ["Theo", "Teddy", "Ted"],
  Thomas: ["Tom", "Tommy"],
  Timothy: ["Tim", "Timmy"],
  Tobias: ["Toby"],
  Tomas: ["Tom"],
  Tomás: ["Tom"],
  Tristan: ["Tris"],
  Valentin: ["Val"],
  Valentine: ["Val"],
  Vincent: ["Vince", "Vinnie"],
  Vincenzo: ["Enzo", "Vinnie"],
  Walter: ["Walt", "Wally"],
  Wesley: ["Wes"],
  Weston: ["Wes"],
  William: ["Will", "Billy", "Liam", "Bill"],
  Wolfgang: ["Wolf"],
  Xavier: ["Xavi", "Zave"],
  Yaroslav: ["Slava"],
  Yonatan: ["Yoni"],
  Zachariah: ["Zach", "Zac"],
  Zachary: ["Zach", "Zac"],

  // ── Either ──
  Alex: ["Lex"],
  Avery: ["Ave"],
  Frankie: ["Frank"],
  Jordan: ["Jordy"],
  Morgan: ["Mo"],
  Riley: ["Ri"],
};
