"""Build us-names.js from the US Social Security Administration baby-name data.

Source: SSA national data (names given to at least 5 babies of one sex in a year),
https://www.ssa.gov/oact/babynames/limits.html. This script reads the SQLite copy
shipped in the `usbabynames` npm package (npm pack usbabynames --ignore-scripts,
then unzip sqlite/us-name-data.sqlite.zip). Only the SSA birth counts are used.

Usage: python3 tools/build_us_names.py path/to/us-name-data.sqlite [year]
"""
import sqlite3
import sys

db_path = sys.argv[1]
year = int(sys.argv[2]) if len(sys.argv) > 2 else None

c = sqlite3.connect(db_path).cursor()
if year is None:
    year = c.execute("SELECT MAX(year) FROM usNameData").fetchone()[0]

rows = c.execute(
    "SELECT name, sex, births FROM usNameData WHERE year = ?", (year,)
).fetchall()

def display(name):
    # SSA stores names lowercase here; SSA's own files capitalise only the first letter
    return name[:1].upper() + name[1:]

girls = sorted(((display(n), b) for n, s, b in rows if s == "F"), key=lambda x: (-x[1], x[0]))
boys = sorted(((display(n), b) for n, s, b in rows if s == "M"), key=lambda x: (-x[1], x[0]))

with open("us-names.js", "w") as out:
    out.write(f"""// US Social Security Administration baby names, {year}: every name given to at
// least 5 babies of one sex. Generated by tools/build_us_names.py; don't edit by hand.
// Format: "Name:births" ordered by births, highest first.
const US_NAMES = {{
  year: {year},
  girls: '{",".join(f"{n}:{b}" for n, b in girls)}',
  boys: '{",".join(f"{n}:{b}" for n, b in boys)}',
}};
""")

print(f"{year}: {len(girls)} girls' names, {len(boys)} boys' names, "
      f"{len({n for n, _ in girls} | {n for n, _ in boys})} distinct")
